const contractAddress = "0x1b802a03B361A3B43BDe6b175C4eEb9b80C6Ca41"; // Replace with your own contract address
const chain = 'ethereum'; // goerli, polygon, or ethereum

const welcome_h1 = "Papes Have Arrived";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = '8,888 Pixel Apes from deep in the heart of the jungle who wandered onto the Ethereum Blockchain.';
const h1_presale_coming_soon = "Papes Coming Soon";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Minting Open";
const h2_presale_coming_soon = "Minting Countdown";
const h2_presale_mint = "Minting Countdown";
const p_presale_coming_soon = "Stay Tuned ;)";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "Mint Your Papes Below 🦍";
const button_presale_coming_soon = "Join the Discord";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Join the Discord";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your Papes";
const mint_failed = "Minting failed. 😢 Please try again.";
